### ISSUE TITLE
Create Ruby OSS Index client MVP

### ISSUE THREAD

**Issue by ken-duck** [sonatype-nexus-community/chelsea#1]
Create a Ruby OSS Index client, with the following features:

- Command line tool
- Written in Ruby

Basic Features
---------------
- Reads package dependencies from the appropriate Ruby package file(s)
    - Preferably determines transitive dependencies
- Request known vulnerabilities for the dependencies from OSS Index.
    - Use the POST API at OSS Index
    - Note the maximum of 128 packages per request
- Report to console the packages scanned and detected vulnerabilities, in the style of other OSS Index command line auditing tools

**Comment by DarthHater** [comment]
This is done, closing in favor of more granular issues.
